name: Node.js CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
<<<<<<< /Users/doberkofler/MyShare/doberkofler/depvital/.github/workflows/node.js.yml
          node-version: '22.x'
          cache: 'pnpm'
      - run: 'pnpm install --frozen-lockfile'
      - run: 'pnpm run ci'
=======
          node-version: "22.x"
          cache: "pnpm"
      - run: "pnpm install --frozen-lockfile"
      
      - run: "pnpm run ci"
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
>>>>>>> /Users/doberkofler/MyShare/doberkofler/depvital/.github/workflows/node.js.yml.new.tmp
